
export const ADMIN_TICKET_NOTIFICATION_TEMPLATE = `
  <div style="
    font-family: Arial, Helvetica, sans-serif;
    max-width: 650px;
    margin: auto;
    background-color: #f4f6fb;
    padding: 30px;
    border-radius: 12px;
  ">

    <!-- Header -->
    <div style="
      background: linear-gradient(135deg, #dc2626, #ef4444);
      padding: 25px;
      border-radius: 10px;
      text-align: center;
      color: #ffffff;
    ">
      <h1 style="margin: 0; font-size: 26px;">
        🚨 New Support Ticket Raised
      </h1>

      <p style="margin-top: 8px; font-size: 14px;">
        A new support request has been submitted by a user
      </p>
    </div>

    <!-- Main Content -->
    <div style="
      background-color: #ffffff;
      padding: 25px;
      margin-top: 20px;
      border-radius: 10px;
      color: #333;
      line-height: 1.6;
    ">

      <h2 style="margin-top: 0; color: #111827;">
        📌 Ticket Information
      </h2>

      <div style="
        background-color: #f9fafb;
        border: 1px solid #e5e7eb;
        border-radius: 8px;
        padding: 20px;
        margin-top: 15px;
      ">

        <p style="margin: 10px 0; font-size: 14px;">
          <strong>User Name:</strong> {name}
        </p>

        <p style="margin: 10px 0; font-size: 14px;">
          <strong>User Email:</strong> {email}
        </p>

        <p style="margin: 10px 0; font-size: 14px;">
          <strong>Subject:</strong> {subject}
        </p>

        <p style="margin: 10px 0; font-size: 14px;">
          <strong>Status:</strong>

          <span style="
            background-color: #facc15;
            color: #111827;
            padding: 4px 10px;
            border-radius: 20px;
            font-size: 12px;
            font-weight: bold;
          ">
            Pending
          </span>
        </p>

        <div style="margin-top: 18px;">
          <strong style="font-size: 14px;">
            Message:
          </strong>

          <div style="
            margin-top: 10px;
            background-color: #ffffff;
            border-left: 4px solid #2563eb;
            padding: 15px;
            color: #555;
            font-size: 14px;
            border-radius: 6px;
          ">
            {message}
          </div>
        </div>
      </div>

      <!-- Action Section -->
      <div style="
        margin-top: 30px;
        text-align: center;
      ">
        <a href="#"
          style="
            display: inline-block;
            background-color: #2563eb;
            color: #ffffff;
            padding: 14px 26px;
            text-decoration: none;
            border-radius: 8px;
            font-size: 15px;
            font-weight: bold;
          ">
          Open Admin Dashboard →
        </a>
      </div>

    </div>

    <!-- Footer -->
    <p style="
      font-size: 12px;
      color: #888;
      text-align: center;
      margin-top: 25px;
    ">
      This email was automatically generated by the Support Ticket System.<br/>
      © ${new Date().getFullYear()} Support Ticket System.
    </p>

  </div>
`;

export const sendTicketRaisedEmailToAdminTemplate = () => ADMIN_TICKET_NOTIFICATION_TEMPLATE;

